quickemu-project/quickgui

- pubspec.yaml
git:// was causing network errors and timing out/wouldn't install with 'flutter pub get'
> pubspec.yaml: Changed git url from git:// to https:// 

- lib/main.dart
- lib/src/app.dart
- lib/src/globals.dart
- lib/src/mixins/preferences_mixin.dart
- lib/src/pages/downloader.dart
- lib/src/pages/manager.dart
- lib/src/widgets/home_page/downloader_menu.dart
- pubspec.yaml
Refactored shared preferences functions to be generic setters/getters using key/values to allow for multiple preferences to be stored. Refactored the shared preferences functions as a mixin for ease of use. Directory change is now remembered across the app pages.
> Mixin preferences: Refactored shared preferences functions to be generic setters/getters used as a mixin

- lib/src/pages/manager.dart
This squashes a potential bad interaction on initial launch that causes at the least a message in the terminal about using a null value instead of string.
> Small nullability check in manager.dart for null working directory

- lib/src/widgets/home_page/home_page_button_group.dart
e.g. Arch Linux only has `latest` available. We can preselect `latest` in this instance.
> Preselect the version when only one version is available

- lib/main.dart
- lib/src/app.dart
- lib/src/i18n/i18n_ext.dart
- lib/src/i18n/quickgui_localizations_delegate.dart
- lib/src/model/operating_system.dart
- lib/src/model/version.dart
- lib/src/pages/downloader.dart
- lib/src/pages/downloader_page.dart
- lib/src/pages/main_page.dart
- lib/src/pages/manager.dart
- lib/src/pages/operating_system_selection.dart
- lib/src/pages/option_selection.dart
- lib/src/pages/version_selection.dart
- lib/src/widgets/downloader/cancel_dismiss_button.dart
- lib/src/widgets/downloader/download_label.dart
- lib/src/widgets/home_page/downloader_menu.dart
- lib/src/widgets/home_page/home_page_button_group.dart
- lib/src/widgets/home_page/main_menu.dart
- lib/src/widgets/left_menu.dart
Following best practice from https://dart.dev/guides/libraries/create-library-packages local imports should not reference our package name, but use relative paths.
> Use local imports, not package imports for our own files

- assets/images/console.svg
- lib/src/pages/manager.dart
- pubspec.yaml
This branch makes the following changes:
- Removes the "Use SPICE" button for each VM in favour of passing `--display spice` by default if the `spicy` client is installed
- Adds a new button to running VMs, to reconnect the display with `spicy`, if it's installed.
- Adds a new button to running VMs, to connect via an SSH session if an SSH server is detected on the guest. This will use the terminal emulator set as `x-terminal-emulator`
- Does some styling changes to the buttons to make them look more consistent with the rest of the app (pink accent for active buttons, etc).
This does add a new SVG icon, and thus the flutter_svg package, to display a console icon for the SSH button. We might want to review this if we include the Yaru icons or another icon set as suggested in #8.
Once …
> Add new action buttons for running VMs

- assets/i18n/pt_PT.po
- lib/src/supported_locales.dart
Added Portuguese European (pt_PT) translation file to assets/i18n and also edited lib/src/supported_locales.dart to include new pt_PT locale
> Added Portuguese European (pt_PT) translation

- LICENSE
A license file was not originally not included with the repo, however based on the "packaging" repo, this does seem to have been intended as MIT.
This PR just includes the same MIT License file used there.
> Add license file based on packaging repo license

- README.md
Updated URLs to `quickemu-project` github repositories and corrected some texts.
> Updated URLs

- lib/main.dart
- Close #124
`quickemu list_csv` is deprecated and `quickemu --list-csv` provide the same functionality.
> refactor: update loadOperatingSystems to use quickget --list-csv

- lib/main.dart
- lib/src/pages/downloader.dart
- lib/src/widgets/downloader/download_label.dart
Since Quickemu 4.9.3 `quickget` downloads everything, except Ubuntu daily images, with curl via the `web_get()` function internal to `quickget`.
This pull request drops support for `wget`, `aria2` and `macrecovery` progress parsing as none of these are used by `quickget` anymore. It also adapts the progress parsing to `curl`'s progress output and accounts for a bug in `quickget` where it stopped reporting if `wget`/`curl` is the external download tool in the csv data.
> fix: update download progress parsing to support curl's output

- lib/src/model/app_settings.dart
- lib/src/widgets/left_menu.dart
Dark mode doesn't render some icons correctly at the moment and in an effort to get an update Quickgui release out light mode the temporarily the only theme.
> chore: temporarily force light mode

- lib/src/model/app_settings.dart
- lib/src/widgets/left_menu.dart
> style: make theme switching inactive and enable light theme by default

- lib/src/widgets/left_menu.dart
While the menu slides in from the left it causes the whole app to flicker and stutter.
This patch caches the `supportedLocales` at `initState()` and replaces `Divider()` with `Container()`. The two `Divider()` were largely responsible for the ugly flickering and replacing the with `Conatiner()` keeps things flicker free.
> fix: prevent flickering while left_menu slides in

- .github/workflows/build-quickgui.yml
Test builds of the Quickgui Flutter app are always being triggered. This patch only triggers test builds of the app, if the app was actually changed.
> ci: only test build quickgui if the flutter app was changed

- lib/src/globals.dart
- lib/src/widgets/left_menu.dart
The patch adds `fetchQuickemuVersion()` and uses it to display the Quickemu version being used by Quickgui. 
- Resolves #169
> feat: add fetchQuickemuVersion() and display version in the menu

- lib/src/pages/manager.dart
- pubspec.lock
- pubspec.lock.json
- pubspec.yaml
This patch checks the available Quickemu version. If >= 4.9.6 is available, Quickgui will use the new Quickemu `--kill` option to terminate VMs. The existing `killall <processname>` will be used for older versions of Quickemu.
This change is being made because `--kill` is macOS compatible, whereas `killall <processname>` is only supported on Linux because QEMU on macOS can not set the process name for a VM.
- Resolves #170
> feat: kill VMs using quickemu --kill when running quickemu >= 4.9.6

- flake.lock
- flake.nix
This updates the Nix flake to include the current stable release of Quickemu via the FlakeHub flake and always tracks the Nixpkgs stable branch.
- All future Quickgui releases will now also include the stable release of Quickemu.
- Nix devshell now have the current Quickemu version included, directly from us (upstream) rather than potentially out-of-date releases from Nixpkgs
- The builds tool in the Nix devshell track the 6-monthly stable branch of Nixpkgs for better predictability.
> feat: nix package, overlay and devshell use the quickemu FlakeHub flake

- assets/i18n/cs_CZ.po
- assets/i18n/cy.po
- assets/i18n/de.po
- assets/i18n/en.po
- assets/i18n/es.po
- assets/i18n/fr.po
- assets/i18n/gd.po
- assets/i18n/hu.po
- assets/i18n/it.po
- assets/i18n/ja.po
- assets/i18n/nl.po
- assets/i18n/no.po
- assets/i18n/oc.po
- assets/i18n/pt_BR.po
- assets/i18n/pt_PT.po
- assets/i18n/quickgui.pot
- assets/i18n/ru.po
- assets/i18n/sv.po
- assets/i18n/tr.po
A whitespace has been added to a localizable message in the code, but the .po files have not been updated.
> fix: localizations

- lib/src/pages/manager.dart
Change how VM processes are inspected to test if they are running but using `kill -0 <pid>`. Use `kill -0` is portable between macOS and Linux and the BSD and GNU tools. `quickemu` also uses `kill -0`, which was introduced as part of the macOS porting work.
I've tested this on Linux to make sure there are no regressions; it needs validating on macOS.
- Fixes #179
> fix: check for running VM processes using kill -0

- README.md
Went through the installation and found that there is a typo in the README.
```
$ sudo add-apt-repository ppa:flexiondotorg/quickgui
ERROR: ppa 'flexiondotorg/quickgui' not found (use --login if private)
```
But with the quickemu instructions it all work:
```
$ sudo apt-add-repository ppa:flexiondotorg/quickemu
...
$ sudo apt-get install quickgui
(all good)
```
Seems that the right ppa is the same as the one for quickemu and one with `quickgui` in it.
- Related #196 (ticket seems related, although they mention Asahi, I am on vanilla Ubuntu)
> docs: fix Ubuntu ppa repository name

- CONTRIBUTING.md
Point the contributors towards project-level discussion rather than a 404.
- Closes #204
( if a project wiki is enabled)
> fix: repoint CONTRIBUTING discussion link

- lib/src/app.dart
- lib/src/widgets/left_menu.dart
This PR changes the primary color of the dark theme to improve the contrast. Additionally, the dark mode switch has been re-enabled so users can toggle the dark mode again. The design of the dark mode switch has also been slightly adjusted for a more refined appearance.
- Closes # 144
*`yq` above is [yq-go](https://github.com/mikefarah/yq)*
> feat(theme): update primary color for improved dark mode contrast
